version: '3'
services: 
    flask:
        build: flask
        ports: 
            - 5000:5000
    nginx:
        build: nginx
        ports:
            - 80:80
        volumes:
            - /var/log/nginx:/var/log/nginx
    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./prometheus:/etc/prometheus/
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
    node-exporter:
        image: prom/node-exporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
        ports:
            - 9100:9100
    grafana:
        image: grafana/grafana:latest
        volumes:
            - ./data/grafana:/var/lib/grafana
        ports: 
            - 3000:3000
